# Generated by Django 2.0.2 on 2018-03-05 13:31

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(verbose_name='내용')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(verbose_name='내용')),
                ('title', models.CharField(help_text='제목을 입력해주세요. 100자 내외', max_length=100, verbose_name='제목')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoffeeEducation',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='postings.Post')),
                ('people_number', models.PositiveIntegerField()),
                ('participants', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=models.PositiveIntegerField())),
                ('meeting_date', models.DateTimeField()),
                ('category', models.CharField(choices=[('d', '드립 교육'), ('c', '커핑 교육'), ('e', '에스프레소 교육'), ('a', '운영진 교육')], max_length=1, verbose_name='교육 분류')),
                ('difficulty', models.CharField(blank=True, choices=[('e', '기초'), ('h', '심화')], max_length=1, null=True, verbose_name='난이도')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='교육 장소')),
            ],
            options={
                'abstract': False,
            },
            bases=('postings.post',),
        ),
        migrations.CreateModel(
            name='CoffeeMeeting',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='postings.Post')),
                ('people_number', models.PositiveIntegerField()),
                ('participants', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=models.PositiveIntegerField())),
                ('meeting_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
            bases=('postings.post',),
        ),
        migrations.CreateModel(
            name='OfficialEvent',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='postings.Post')),
                ('people_number', models.PositiveIntegerField()),
                ('participants', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=models.PositiveIntegerField())),
                ('meeting_date', models.DateTimeField()),
                ('category', models.CharField(choices=[('i', '동소제'), ('w', '신환회'), ('m', 'MT'), ('k', '장터')], max_length=1)),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='행사 장소')),
            ],
            options={
                'abstract': False,
            },
            bases=('postings.post',),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postings.Post'),
        ),
    ]
