# Generated by Django 2.0.2 on 2018-03-07 01:54

import django.contrib.postgres.fields
from django.db import migrations, models
import postings.models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeeducation',
            name='participants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None, validators=[postings.models.Meeting.participant_validator], verbose_name='참석자'),
        ),
        migrations.AlterField(
            model_name='coffeemeeting',
            name='participants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None, validators=[postings.models.Meeting.participant_validator], verbose_name='참석자'),
        ),
        migrations.AlterField(
            model_name='officialevent',
            name='participants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None, validators=[postings.models.Meeting.participant_validator], verbose_name='참석자'),
        ),
    ]
