# Generated by Django 2.0.4 on 2018-04-30 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerMeeting',
            fields=[
                ('meeting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='meetings.Meeting')),
                ('old_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ActiveUser', verbose_name='위짝지')),
            ],
            options={
                'abstract': False,
            },
            bases=('meetings.meeting',),
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('partner_year', models.PositiveIntegerField(default=2018, verbose_name='짝지 년도')),
                ('partner_semester', models.PositiveIntegerField(choices=[(1, '1학기'), (2, '2학기')], verbose_name='짝지 학기')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='점수')),
                ('new_partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='new_partner', to='accounts.ActiveUser', verbose_name='아래짝지')),
                ('old_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_partner', to='accounts.ActiveUser', verbose_name='위짝지')),
            ],
            options={
                'verbose_name': '짝지',
                'verbose_name_plural': '짝지',
            },
        ),
    ]
