# Generated by Django 2.0.2 on 2018-03-11 01:44

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20180311_1044'),
        ('postings', '0002_auto_20180311_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner_Meeting',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='postings.Post')),
                ('participants', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None, verbose_name='참석자')),
                ('meeting_date', models.DateField(verbose_name='짝모 날짜')),
            ],
            options={
                'abstract': False,
            },
            bases=('postings.post',),
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('partner_year', models.PositiveIntegerField(default=2018, verbose_name='짝지 년도')),
                ('partner_semester', models.PositiveIntegerField(choices=[(1, '1학기'), (2, '2학기')], verbose_name='짝지 학기')),
                ('new_partner', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=3, verbose_name='아래짝지')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='점수')),
                ('old_partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='old_partner', to='accounts.ActiveUser', verbose_name='위짝지')),
            ],
            options={
                'verbose_name': '짝지',
                'verbose_name_plural': '짝지',
            },
        ),
        migrations.AddField(
            model_name='partner_meeting',
            name='partners',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.Partners', verbose_name='짝지'),
        ),
    ]
