# Generated by Django 2.0.2 on 2018-03-05 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activeuser',
            old_name='create_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='activeuser',
            old_name='modified_at',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='partners',
            old_name='create_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='partners',
            old_name='modified_at',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='create_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='modified_at',
            new_name='modified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_first_paid',
        ),
        migrations.AlterField(
            model_name='activeuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='new_partner1',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_partner1', to='accounts.ActiveUser', verbose_name='아래짝지1'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='new_partner2',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_partner2', to='accounts.ActiveUser', verbose_name='아래짝지2'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='new_partner3',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_partner3', to='accounts.ActiveUser', verbose_name='아래짝지3'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='old_partner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='old_partner', to='accounts.ActiveUser', verbose_name='위짝지'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='activeuser',
            unique_together={('user', 'last_active_year', 'last_active_semester')},
        ),
    ]
