# Generated by Django 2.0.2 on 2018-03-06 11:07

import accounts.models
import accounts.validators
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeuser',
            name='active_year',
            field=models.DateField(default=2018, verbose_name='활동년도'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='enroll_year',
            field=models.PositiveIntegerField(default=2018, verbose_name='가입년도'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(help_text='01x-xxxx-xxxx 형식으로 적어주세요', max_length=20, validators=[accounts.validators.phone_validator], verbose_name='휴대폰번호'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=accounts.models.get_profile_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_no',
            field=models.CharField(help_text='20xx-xxxxx 형식으로 적어주세요', max_length=12, validators=[accounts.validators.student_no_validator], verbose_name='학번'),
        ),
    ]
