# Generated by Django 2.0.4 on 2018-04-30 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafe', '0001_initial'),
        ('accounts', '0001_initial'),
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='postings.Post')),
                ('people_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='참석 인원')),
                ('meeting_date', models.DateField(verbose_name='모임 일시')),
            ],
            options={
                'abstract': False,
            },
            bases=('postings.post',),
        ),
        migrations.CreateModel(
            name='CoffeeEducation',
            fields=[
                ('meeting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='meetings.Meeting')),
                ('category', models.CharField(choices=[('d', '드립 교육'), ('c', '커핑 교육'), ('e', '에스프레소 교육'), ('a', '운영진 교육')], max_length=1, verbose_name='교육 분류')),
                ('difficulty', models.CharField(blank=True, choices=[('e', '기초'), ('h', '심화')], max_length=1, null=True, verbose_name='난이도')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='교육 장소')),
            ],
            options={
                'abstract': False,
            },
            bases=('meetings.meeting',),
        ),
        migrations.CreateModel(
            name='CoffeeMeeting',
            fields=[
                ('meeting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='meetings.Meeting')),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cafe.Cafe')),
            ],
            options={
                'abstract': False,
            },
            bases=('meetings.meeting',),
        ),
        migrations.CreateModel(
            name='OfficialEvent',
            fields=[
                ('meeting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='meetings.Meeting')),
                ('category', models.CharField(choices=[('i', '동소제'), ('w', '신환회'), ('m', 'MT'), ('k', '장터')], max_length=1)),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='행사 장소')),
            ],
            options={
                'abstract': False,
            },
            bases=('meetings.meeting',),
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(to='accounts.ActiveUser'),
        ),
    ]
